### ISSUE TITLE
Pre-Launch Checklist

### ISSUE THREAD

**Issue by WEP11** [WEP11/UNC-Charlotte-Meteorology-Website#18]
- [x] Fix 48 Hour Current Conditions Graph Bug ([Maybe related to this](https://github.com/WEP11/UNC-Charlotte-Meteorology-Website/blob/2b6a5e7b0709c385f8032f771b8a0047ea30034a/js/currentConditions.js#L92-L96))
- [x] Homepage - Revisit current conditions image shape
- [x] Resources - Footer is being violated by CSS
- [x] Sitewide - Revisit Mobile Options? Maybe?
- [x] STORM - White description text
- [x] Chi Epsilon Pi - White description text
- [x] Faculty - Brian Magi 404

**Comment by WEP11** [comment]
Begin launch sequence!
